### ISSUE TITLE
Defining the board

### ISSUE THREAD

**Issue by rohitmucherla** [everettyang/python-checkers#2]
Pseudo code for defining the board and what goes into that

**Comment by awolowomay** [comment]
Direction, Squares, size, positions, color---> id a size ( X and O), edges

**Comment by awolowomay** [comment]
Direction and position are  very confusing concepts for me to define within the code

**Comment by awolowomay** [comment]
[check1.pdf](https://github.com/everettyang/python-checkers/files/534790/check1.pdf)
