### ISSUE TITLE
Algorithms (general)

### ISSUE THREAD

**Issue by rohitmucherla** [everettyang/python-checkers#3]
Algorithms for the game - which ones we need / things we need to think about

**Comment by Tuckermatis** [comment]
https://docs.google.com/document/d/1CKoXF_1v7O3RmkhxairQLf3DZPT-AmF36Wa58YOK8Bs/edit

**Comment by RobertShannonXC** [comment]
https://docs.google.com/a/tamu.edu/document/d/1CKoXF_1v7O3RmkhxairQLf3DZPT-AmF36Wa58YOK8Bs/edit?usp=sharing
