### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by rohitmucherla** [everettyang/python-checkers#5]
what goes into the graphical interface

**Comment by patelneal** [comment]
## Interface 
#### There isn't really any pseudocode as each object created in the interface is just an instance of a specific class
- Class for an individual board square
 - An array of board squares will be used for instantiating the board object
- Class for board object
 - Will be instantiated with a specific radius (height and width will always be the same)
- Class for player object
 - Be instantiated with a specific username
- Class for checkers piece
 - Instantiate with position ({x, y} coordinate)
- Perhaps use a GUI library to incorporate with game engine (idea is to use PyGame module)
